word =  input()
leng = len(word)
leng -= word.count('c=')
leng -= word.count('c-')
leng -= word.count('dz=')
leng -= word.count('d-')
leng -= word.count('lj')
leng -= word.count('nj')
leng -= word.count('s=')
leng -= word.count('z=')
print(leng)